version: "3.9"

services:
  greeting-service:
    build:
      context: ./greeting-service
      args:
        MY_VAR: ${PORT_SERVICE1}
    ports:
      - ${PORT_SERVICE1}:${PORT_SERVICE1}
    env_file:
      - ./greeting-service/.env # Load environment variables from the .env file
  name-service:
    build:
      context: ./name-service
      args:
        MY_VAR: ${PORT_SERVICE2}
    ports:
      - ${PORT_SERVICE2}:${PORT_SERVICE2}
    env_file:
      - ./name-service/.env # Load environment variables from the .env file
  api-gateway:
    build:
      context: ./api-gateway
      args:
        MY_VAR: ${PORT_SERVICE3}
    ports:
      - ${PORT_SERVICE3}:${PORT_SERVICE3}
    depends_on:
      - greeting-service
      - name-service
    env_file:
      - ./api-gateway/.env # Load environment variables from the .env file
